# Generated by Django 4.0.3 on 2022-03-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clintes',
            name='tfno',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
