# Generated by Django 4.0.3 on 2022-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clintes_tfno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clintes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La dirección'),
        ),
    ]
